version: '3.5'
volumes:
  portainer_data:
services:
  game-frontend:
    image: shkip/private:game-frontend
    container_name: game-frontend
    restart: always
    ports:
       - 4444:80
  game-backend:
    image: shkip/private:game-backend
    container_name: game-backend
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=game-mongo
    ports:
       - 3333:3000
    depends_on:
      - game-mongo
    links:
      - game-mongo
  game-mongo:
    image: mongo
    container_name: game-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_LOGIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 127.0.0.1:${MONGO_PORT}:27017
    volumes:
      - ./data/mongo-db:/data/db